const duration1500 = Duration(milliseconds: 1500);
const duration1200 = Duration(milliseconds: 1200);
const duration800 = Duration(milliseconds: 800);
const duration700 = Duration(milliseconds: 700);
const duration500 = Duration(milliseconds: 500);
const duration300 = Duration(milliseconds: 300);
const duration200 = Duration(milliseconds: 200);
const duration100 = Duration(milliseconds: 100);
const duration50 = Duration(milliseconds: 500);
const duration1 = Duration(seconds: 1);
const duration2 = Duration(seconds: 2);
const duration5 = Duration(seconds: 5);
const duration10 = Duration(seconds: 10);
const duration0 = Duration.zero;

const duration1min = Duration(minutes: 1);
const duration2min = Duration(minutes: 2);
const duration1hour = Duration(hours: 1);
const otpDuration = Duration(minutes: 1);
